import { ArrowDownRight, ArrowUpRight, MoveUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import { AcademicCard } from "../../components/content/AcademicCard";
import { SectionHeader } from "../../components/content/SectionHeader";
import { useContent, useSite } from "../../hooks/use-platform-data";

export function HomePage() {
  const { data: site } = useSite(); const { data: content } = useContent();
  return <div className="home-page"><section className="hero-v2"><div className="hero-copy-v2"><p className="eyebrow">Professor · Systems researcher · Educator</p><h1>Building ways to <em>see</em> how systems think.</h1><p className="hero-lede">{site?.profile.bio}</p><div className="hero-actions"><Link className="button" to="/research">Explore the work <ArrowUpRight size={17} /></Link><Link className="quiet-link" to="/about">Read the story <ArrowDownRight size={16} /></Link></div></div><div className="hero-instrument"><div className="instrument-label"><span>LAB / 01</span><span>LIVE SYSTEMS</span></div><div className="signal-grid"><span className="signal-line line-a" /><span className="signal-line line-b" /><span className="signal-node node-a" /><span className="signal-node node-b" /><span className="signal-node node-c" /><div className="instrument-readout"><span>EDGE SIGNAL</span><strong>0.847</strong><small>stable / 24.8° C</small></div></div><div className="instrument-footer"><span>Interactive Systems & Learning Lab</span><MoveUpRight size={17} /></div></div></section><section className="stats-strip">{site?.stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</section><section className="home-section"><SectionHeader eyebrow="Research / 01" title="Questions with a physical edge" intro="The lab works where computation meets the constraints of the real world: energy, signal, time, and human attention." action={<Link className="text-link" to="/research">All research <ArrowUpRight size={15} /></Link>} /><div className="research-grid">{site?.researchAreas.map(area => <article className={`research-card ${area.tone}`} key={area.id}><span className="research-number">{area.number}</span><h3>{area.title}</h3><p>{area.summary}</p><span className="research-detail">{area.detail}</span><ArrowUpRight className="card-arrow" size={18} /></article>)}</div></section><section className="home-section home-section-dark"><SectionHeader eyebrow="Selected work / 02" title="From prototype to practice" action={<Link className="text-link light" to="/projects">View projects <ArrowUpRight size={15} /></Link>} /><div className="project-feature-grid">{site?.featuredProjects.map(project => <article className={`project-feature ${project.color}`} key={project.id}><div><span className="project-tag">{project.tag}</span><h3>{project.title}</h3><p>{project.summary}</p></div><span className="project-year">{project.year}</span></article>)}</div></section><section className="home-section"><SectionHeader eyebrow="Writing / 03" title="Notes from the lab" action={<Link className="text-link" to="/journal">Read the journal <ArrowUpRight size={15} /></Link>} /><div className="article-list">{content?.filter(item => item.type === "blog").map(item => <AcademicCard key={item.id} item={item} />)}</div></section></div>;
}
